"""Pydantic models for AI Ops Platform."""

from datetime import datetime
from enum import Enum
from typing import Any, Optional
from pydantic import BaseModel, Field
import uuid


class AgentType(str, Enum):
    GOOGLE_ADS = "google_ads"
    SEO_CONTENT = "seo_content"
    COMPETITOR = "competitor"


class RecommendationStatus(str, Enum):
    PENDING = "pending"
    APPROVED = "approved"
    SKIPPED = "skipped"
    EXECUTED = "executed"
    FAILED = "failed"


class Priority(str, Enum):
    HIGH = "high"
    MEDIUM = "medium"
    LOW = "low"


class ContentStatus(str, Enum):
    DRAFT = "draft"
    APPROVED = "approved"
    SENT = "sent"
    PUBLISHED = "published"


class JobStatus(str, Enum):
    RUNNING = "running"
    COMPLETED = "completed"
    FAILED = "failed"


class Recommendation(BaseModel):
    """A recommendation generated by an agent."""

    id: str = Field(default_factory=lambda: str(uuid.uuid4()))
    agent: AgentType
    type: str
    status: RecommendationStatus = RecommendationStatus.PENDING
    priority: Priority = Priority.MEDIUM
    title: str
    summary: Optional[str] = None
    details: dict[str, Any] = Field(default_factory=dict)
    created_at: datetime = Field(default_factory=datetime.utcnow)
    reviewed_at: Optional[datetime] = None
    reviewed_by: Optional[str] = None
    executed_at: Optional[datetime] = None

    def to_db_dict(self) -> dict:
        """Convert to dict for Supabase insert."""
        return {
            "id": self.id,
            "agent": self.agent.value,
            "type": self.type,
            "status": self.status.value,
            "priority": self.priority.value,
            "title": self.title,
            "summary": self.summary,
            "details": self.details,
            "created_at": self.created_at.isoformat(),
        }


class Action(BaseModel):
    """A record of an executed action."""

    id: str = Field(default_factory=lambda: str(uuid.uuid4()))
    recommendation_id: Optional[str] = None
    agent: AgentType
    action_type: str
    title: Optional[str] = None
    description: Optional[str] = None
    impact: Optional[str] = None
    result: Optional[str] = None  # "success", "failed", "partial"
    error_message: Optional[str] = None
    metadata: dict[str, Any] = Field(default_factory=dict)
    executed_at: datetime = Field(default_factory=datetime.utcnow)

    def to_db_dict(self) -> dict:
        """Convert to dict for Supabase insert."""
        return {
            "id": self.id,
            "recommendation_id": self.recommendation_id,
            "agent": self.agent.value,
            "action_type": self.action_type,
            "title": self.title,
            "description": self.description,
            "impact": self.impact,
            "result": self.result,
            "error_message": self.error_message,
            "metadata": self.metadata,
            "executed_at": self.executed_at.isoformat(),
        }


class PerformanceSnapshot(BaseModel):
    """Daily performance metrics snapshot."""

    id: str = Field(default_factory=lambda: str(uuid.uuid4()))
    date: str  # YYYY-MM-DD
    source: str  # "google_ads", "organic", etc.
    metrics: dict[str, Any] = Field(default_factory=dict)
    created_at: datetime = Field(default_factory=datetime.utcnow)

    def to_db_dict(self) -> dict:
        """Convert to dict for Supabase insert."""
        return {
            "id": self.id,
            "date": self.date,
            "source": self.source,
            "metrics": self.metrics,
            "created_at": self.created_at.isoformat(),
        }


class Content(BaseModel):
    """A blog article in multiple languages."""

    id: str = Field(default_factory=lambda: str(uuid.uuid4()))
    recommendation_id: Optional[str] = None
    keyword: Optional[str] = None
    slug: Optional[str] = None
    title_en: Optional[str] = None
    title_fr: Optional[str] = None
    title_nl: Optional[str] = None
    content_en: Optional[str] = None
    content_fr: Optional[str] = None
    content_nl: Optional[str] = None
    meta_description_en: Optional[str] = None
    meta_description_fr: Optional[str] = None
    meta_description_nl: Optional[str] = None
    status: ContentStatus = ContentStatus.DRAFT
    sent_to: Optional[str] = None
    sent_at: Optional[datetime] = None
    published_url: Optional[str] = None
    created_at: datetime = Field(default_factory=datetime.utcnow)
    updated_at: datetime = Field(default_factory=datetime.utcnow)

    def to_db_dict(self) -> dict:
        """Convert to dict for Supabase insert."""
        return {
            "id": self.id,
            "recommendation_id": self.recommendation_id,
            "keyword": self.keyword,
            "slug": self.slug,
            "title_en": self.title_en,
            "title_fr": self.title_fr,
            "title_nl": self.title_nl,
            "content_en": self.content_en,
            "content_fr": self.content_fr,
            "content_nl": self.content_nl,
            "meta_description_en": self.meta_description_en,
            "meta_description_fr": self.meta_description_fr,
            "meta_description_nl": self.meta_description_nl,
            "status": self.status.value,
            "sent_to": self.sent_to,
            "sent_at": self.sent_at.isoformat() if self.sent_at else None,
            "published_url": self.published_url,
            "created_at": self.created_at.isoformat(),
            "updated_at": self.updated_at.isoformat(),
        }


class JobRun(BaseModel):
    """Record of an agent job execution."""

    id: str = Field(default_factory=lambda: str(uuid.uuid4()))
    agent: AgentType
    status: JobStatus = JobStatus.RUNNING
    started_at: datetime = Field(default_factory=datetime.utcnow)
    completed_at: Optional[datetime] = None
    summary: dict[str, Any] = Field(default_factory=dict)
    error_message: Optional[str] = None

    def to_db_dict(self) -> dict:
        """Convert to dict for Supabase insert."""
        return {
            "id": self.id,
            "agent": self.agent.value,
            "status": self.status.value,
            "started_at": self.started_at.isoformat(),
            "completed_at": self.completed_at.isoformat() if self.completed_at else None,
            "summary": self.summary,
            "error_message": self.error_message,
        }
